### ISSUE TITLE
花了一天时间，写了一个json 的编辑器

### ISSUE THREAD

**Issue by mannymu** [willnewii/json2canvas#16]
好不容易写了一个编辑器来生成json，然后再小程序上跑你的 demo ，报错了，，是 json2canvas.js 文件报错，头部的兼容旧报错了。

我太难了
![image](https://user-images.githubusercontent.com/15630104/67171583-5c6c2980-f3ea-11e9-8314-24ef17926b7e.png)

**Comment by mannymu** [comment]
后来发现，使用小程序的 npm 构建可以了。。。
顺便贴一下，我的这个可视化编辑json地址
https://gitee.com/muand/myFragment/blob/master/canvas2json/example/web/index1.html

**Comment by willnewii** [comment]
厉害~  厉害！  正准备加这个功能呢~
