### ISSUE TITLE
构建 npm 后，目录中有 cax 目录，442 kb

### ISSUE THREAD

**Issue by shenxiang11** [willnewii/json2canvas#17]
包大小略大啊，如何处理

**Comment by willnewii** [comment]
您说的是 miniprogram_npm/json2canvas  整个目录大小吧,这个并不是实际的打包大小.

您可以先移除这个依赖,然后点一次预览.然后添加这个依赖再预览一次.在详情里看看两次预览的大小差别.  我这边的差值是105Kb.
