### ISSUE TITLE
能支持旋转吗

### ISSUE THREAD

**Issue by a542006055** [willnewii/json2canvas#19]
能支持旋转吗

**Comment by willnewii** [comment]
旋转是个什么需求?

**Comment by a542006055** [comment]
就是图片或文字rotate




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "诗人的咸鱼"<notifications@github.com&gt;; 
发送时间: 2020年3月30日(星期一) 上午10:55
收件人: "willnewii/json2canvas"<json2canvas@noreply.github.com&gt;; 
抄送: "542006055"<542006055@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [willnewii/json2canvas] 能支持旋转吗 (#19)





 
旋转是个什么需求?

**Comment by willnewii** [comment]
不好意思,隔了这么久😅 
新增了一个[rotation属性](https://github.com/willnewii/json2canvas/blob/2741ed38483adf2b7f597774a88b00683c8fb84b/example/web/option.js#L31)

[demo](http://blog.mayday5.me/json2canvas/example/web/index.html)，第二个头像和第二个方框和后面那一段文本是实际效果.
