### ISSUE TITLE
怎么修改参数

### ISSUE THREAD

**Issue by 123siwuliu** [willnewii/json2canvas#9]
首先感谢博主分享，我要实现海报在线编辑功能（将模板放到编辑器中去修改）正头疼就出现了曙光，我想问下，json数据的格式是固定的吗？ 如果是，我怎么去修改

**Comment by willnewii** [comment]
文档里有写呀。是固定的格式,不过您也可以按照自己的需求自行修改.[json2canvas.js](https://github.com/willnewii/json2canvas/blob/master/src/json2canvas.js) 主要内容都在这里了
